---
- name: Set some fact
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: Disable SELinux
  selinux:
      state: disabled

- name: Install packages dependencies
  yum:
    name:
        - epel-release
        - net-tools
        - vim
        - nano
        - wget
        - telnet
        - rsync
        - git
        - python3
        - python3-pip
    state: present

- name: "RedHat | Set facts for Zabbix <= 5.0"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-proxy-{{ zabbix_proxy_database }}"
  when:
    - zabbix_version is version_compare('5.0', '<=')
  tags:
    - zabbix-proxy

- name: "RedHat | Set facts for Zabbix >= 5.4"
  set_fact:
    datafiles_path: "/usr/share/doc/zabbix-sql-scripts/{{ zabbix_proxy_database }}"
  when:
    - zabbix_version is version_compare('5.4', '>=')
  tags:
    - zabbix-proxy

- name: Install Zabbix Repo.
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"

- name: Install Zabbix packeges
  yum:
    name: "{{ packeges }}"
  vars:
    packeges:
    - zabbix-proxy-{{ zabbix_proxy_database }}
    - zabbix-agent
  when: zabbix_version <= 5.0

- name: Install Zabbix packeges
  yum:
    name: "{{ packeges }}"
  vars:
    packeges:
    - zabbix-sql-scripts
    - zabbix-proxy-{{ zabbix_proxy_database }}
    - zabbix-agent
  when: zabbix_version >= 5.4

- name: "RedHat | Install Mysql"
  yum:
    name: mysql-server
    state: present
  when:
    - zabbix_database_creation or zabbix_database_sqlload
    - zabbix_proxy_database == 'mysql'

- name: Install pip packages
  pip:
    name:
        - pymysql
  when:
    - zabbix_database_creation or zabbix_database_sqlload
    - zabbix_proxy_database == 'mysql'

- name: Make sure mysql service is running
  systemd:
    name: mysqld
    state: started
    enabled: yes
  when:
    - ansible_distribution_major_version == '8'

- name: Make sure zabbix-agent service is running
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: Copy zabbix_proxy.conf template 
  template:
    src: zabbix_proxy.conf.j2
    dest: /etc/zabbix/zabbix_proxy.conf

- name: Copy zabbix_agent.conf template 
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: start zabbix agent
